### ISSUE TITLE
只能在main函数中EasyPusher_Create()成功

### ISSUE THREAD

**Issue by feng905** [EasyDarwin/EasyPusher#1]
c++项目，只能在main函数中EasyPusher_Create()成功，在其他线程中，使用类中的成员函数去调用EasyPusher_Create()会失败。
请各位老大解决，

辛苦！

**Comment by gavin1010** [comment]
EasyPusher_Create 调用没有问题，是返回类型超出了int的范围;
正确的调用:
Easy_U32 pusherId = EasyPusher_Create();
或 unsigned int pusherId = EasyPusher_Create();

你的代码写的是 int pusherId = EasyPusher_Create();  返回值超了int的范围，所以printf("%d", pusherid)为负值了;
